- 👋 Hi, I’m @Sashankasekhar
- 👀 I’m interested in ...artificial intelligence.
- 🌱 I’m currently learning plant science.
- 💞️ I’m looking to collaborate mechine learning with artificial intelligence
- 📫 How to reach me ...begood023@gmail.com
